version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://username:password@db:5432/qorpo_database_sample"
      TEST_DATABASE_URL: "postgresql://username:password@test_db:5433/qorpo_database_test"
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: qorpo_database_sample
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
    restart: always

  test_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: qorpo_database_test
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
    restart: always